FROM openjdk:11.0.6-jre-slim

ARG UTOPIA-DB-USERNAME
ARG UTOPIA-DB-PASSWORD
ARG DB-LOCATION
ENV UTOPIA-DB-UNAME = UTOPIA-DB-USERNAME
ENV UTOPIA-DB-PASS = UTOPIA-DB-PASSWORD
ENV DB-LOC = DB-LOCATION
ARG JAR_FILE=target/*.jar

COPY /target/springproject-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
