FROM openjdk:11.0.6-jre-slim

ARG UTOPIA_DB_USERNAME
ARG UTOPIA_DB_PASSWORD
ARG DB_LOCATION
ENV UTOPIA_DB_UNAME = UTOPIA_DB_USERNAME
ENV UTOPIA_DB_PASS = UTOPIA_DB_PASSWORD
ENV DB_LOC = DB_LOCATION
ARG JAR_FILE=target/*.jar

COPY /target/springproject-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
